TESTS = [
    {
        "id": "3.1",
        "section": "Arithmetic",
        "setup": [],
        "input": "3 4 + .",
        "expect": "7 ",
        "match": "exact",
        "note": "Basic addition",
    },
    {
        "id": "3.2",
        "section": "Arithmetic",
        "setup": [],
        "input": "0 0 + .",
        "expect": "0 ",
        "match": "exact",
        "note": "Zero plus zero",
    },
    {
        "id": "3.3",
        "section": "Arithmetic",
        "setup": [],
        "input": "3 -5 + .",
        "expect": "-2 ",
        "match": "exact",
        "note": "Signed addition",
    },
    {
        "id": "3.4",
        "section": "Arithmetic",
        "setup": [],
        "input": "10 3 - .",
        "expect": "7 ",
        "match": "exact",
        "note": "10 - 3 = 7",
    },
    {
        "id": "3.5",
        "section": "Arithmetic",
        "setup": [],
        "input": "3 10 - .",
        "expect": "-7 ",
        "match": "exact",
        "note": "Signed subtraction: 3 - 10 = -7",
    },
    {
        "id": "3.6",
        "section": "Arithmetic",
        "setup": [],
        "input": "6 7 * .",
        "expect": "42 ",
        "match": "exact",
        "note": "Multiplication",
    },
    {
        "id": "3.7",
        "section": "Arithmetic",
        "setup": [],
        "input": "12345 0 * .",
        "expect": "0 ",
        "match": "exact",
        "note": "Multiply by zero",
    },
    {
        "id": "3.8",
        "section": "Arithmetic",
        "setup": [],
        "input": "6 -7 * .",
        "expect": "-42 ",
        "match": "exact",
        "note": "Signed multiply",
    },
    {
        "id": "3.9",
        "section": "Arithmetic",
        "setup": [],
        "input": "17 5 /MOD . .",
        "expect": "3 2 ",
        "match": "exact",
        "note": "TOS=quotient(3), second=remainder(2)",
    },
    {
        "id": "3.10",
        "section": "Arithmetic",
        "setup": [],
        "input": "20 4 /MOD . .",
        "expect": "5 0 ",
        "match": "exact",
        "note": "Exact division; zero remainder",
    },
    {
        "id": "3.11",
        "section": "Arithmetic",
        "setup": [],
        "input": "17 5 / .",
        "expect": "3 ",
        "match": "exact",
        "note": "/ = /MOD SWAP DROP",
    },
    {
        "id": "3.12",
        "section": "Arithmetic",
        "setup": [],
        "input": "17 5 MOD .",
        "expect": "2 ",
        "match": "exact",
        "note": "MOD = /MOD DROP",
    },
    {
        "id": "3.13",
        "section": "Arithmetic",
        "setup": [],
        "input": "10 1- .",
        "expect": "9 ",
        "match": "exact",
        "note": "1- = 1 -",
    },
]
