TESTS = [
    {
        "id": "5.1",
        "section": "Base / Number Representation",
        "setup": [],
        "input": "HEX ff . DEC",
        "expect": "ff ",
        "match": "exact",
        "note": "Hex output is lowercase",
    },
    {
        "id": "5.2",
        "section": "Base / Number Representation",
        "setup": [],
        "input": "HEX 1a DEC .",
        "expect": "26 ",
        "match": "exact",
        "note": "Parse 1a in hex (=26), switch to decimal, then print: verifies base-switch",
    },
    {
        "id": "5.3",
        "section": "Base / Number Representation",
        "setup": [],
        "input": "BASE @ .",
        "expect": "10 ",
        "match": "exact",
        "note": "BASE holds current radix (decimal=10)",
    },
    {
        "id": "5.4",
        "section": "Base / Number Representation",
        "setup": [],
        "input": "HEX 0 . DEC",
        "expect": "0 ",
        "match": "exact",
        "note": "Zero in hex",
    },
    {
        "id": "5.5",
        "section": "Base / Number Representation",
        "setup": [],
        "input": "HEX 1A . DEC",
        "expect": "1a ",
        "match": "exact",
        "note": "Uppercase hex 1A accepted; . outputs in hex mode as 1a",
    },
]
