TESTS = [
    {
        "id": "1.1",
        "section": "Basic Output",
        "setup": [],
        "input": "42 .",
        "expect": "42 ",
        "match": "exact",
        "note": "Basic number print",
    },
    {
        "id": "1.2",
        "section": "Basic Output",
        "setup": [],
        "input": "0 .",
        "expect": "0 ",
        "match": "exact",
        "note": "Zero",
    },
    {
        "id": "1.3",
        "section": "Basic Output",
        "setup": [],
        "input": "-5 .",
        "expect": "-5 ",
        "match": "exact",
        "note": "Negative literal",
    },
    {
        "id": "1.4",
        "section": "Basic Output",
        "setup": [],
        "input": "32767 .",
        "expect": "32767 ",
        "match": "exact",
        "note": "Multi-digit",
    },
    {
        "id": "1.5",
        "section": "Basic Output",
        "setup": [],
        "input": "65 EMIT",
        "expect": "A",
        "match": "exact",
        "note": "ASCII 65 = A",
    },
    {
        "id": "1.6",
        "section": "Basic Output",
        "setup": [],
        "input": "65 EMIT CR 66 EMIT",
        "expect": "A\nB",
        "match": "exact",
        "note": "CR = 10 EMIT; A then newline then B",
    },
    {
        "id": "1.7",
        "section": "Basic Output",
        "setup": [],
        "input": "65 EMIT SPACE 66 EMIT",
        "expect": "A B",
        "match": "exact",
        "note": "SPACE = 32 EMIT",
    },
]
