TESTS = [
    {
        "id": "4.1",
        "section": "Comparison",
        "setup": [],
        "input": "3 5 < .",
        "expect": "1 ",
        "match": "exact",
        "note": "3 < 5 -> true",
    },
    {
        "id": "4.2",
        "section": "Comparison",
        "setup": [],
        "input": "5 3 < .",
        "expect": "0 ",
        "match": "exact",
        "note": "5 < 3 -> false",
    },
    {
        "id": "4.3",
        "section": "Comparison",
        "setup": [],
        "input": "5 5 < .",
        "expect": "0 ",
        "match": "exact",
        "note": "Equal is not less-than",
    },
    {
        "id": "4.4",
        "section": "Comparison",
        "setup": [],
        "input": "7 3 > .",
        "expect": "1 ",
        "match": "exact",
        "note": "7 > 3 -> true",
    },
    {
        "id": "4.5",
        "section": "Comparison",
        "setup": [],
        "input": "2 8 > .",
        "expect": "0 ",
        "match": "exact",
        "note": "2 > 8 -> false",
    },
    {
        "id": "4.6",
        "section": "Comparison",
        "setup": [],
        "input": "5 5 > .",
        "expect": "0 ",
        "match": "exact",
        "note": "Equal is not greater-than",
    },
    {
        "id": "4.7",
        "section": "Comparison",
        "setup": [],
        "input": "4 4 = .",
        "expect": "1 ",
        "match": "exact",
        "note": "Equal",
    },
    {
        "id": "4.8",
        "section": "Comparison",
        "setup": [],
        "input": "4 5 = .",
        "expect": "0 ",
        "match": "exact",
        "note": "Not equal",
    },
    {
        "id": "4.9",
        "section": "Comparison",
        "setup": [],
        "input": "0 0= .",
        "expect": "1 ",
        "match": "exact",
        "note": "Zero is zero",
    },
    {
        "id": "4.10",
        "section": "Comparison",
        "setup": [],
        "input": "42 0= .",
        "expect": "0 ",
        "match": "exact",
        "note": "Non-zero is not zero",
    },
    {
        "id": "4.11",
        "section": "Comparison",
        "setup": [],
        "input": "0 NOT .",
        "expect": "1 ",
        "match": "exact",
        "note": "NOT = 0=",
    },
    {
        "id": "4.12",
        "section": "Comparison",
        "setup": [],
        "input": "5 5 <= .",
        "expect": "1 ",
        "match": "exact",
        "note": "Boundary: <= via > NOT",
    },
    {
        "id": "4.13",
        "section": "Comparison",
        "setup": [],
        "input": "5 5 >= .",
        "expect": "1 ",
        "match": "exact",
        "note": "Boundary: >= via < NOT",
    },
    {
        "id": "4.14",
        "section": "Comparison",
        "setup": [],
        "input": "3 4 <> .",
        "expect": "1 ",
        "match": "exact",
        "note": "Not equal -> true",
    },
    {
        "id": "4.15",
        "section": "Comparison",
        "setup": [],
        "input": "7 7 <> .",
        "expect": "0 ",
        "match": "exact",
        "note": "Equal -> not-unequal",
    },
    {
        "id": "4.16",
        "section": "Comparison",
        "setup": [],
        "input": "-1 0< .",
        "expect": "1 ",
        "match": "exact",
        "note": "Negative is < 0",
    },
    {
        "id": "4.17",
        "section": "Comparison",
        "setup": [],
        "input": "1 0< .",
        "expect": "0 ",
        "match": "exact",
        "note": "Positive is not < 0",
    },
    {
        "id": "4.18",
        "section": "Comparison",
        "setup": [],
        "input": "5 0> .",
        "expect": "1 ",
        "match": "exact",
        "note": "Positive is > 0",
    },
    {
        "id": "4.19",
        "section": "Comparison",
        "setup": [],
        "input": "3 0<> .",
        "expect": "1 ",
        "match": "exact",
        "note": "Non-zero is <> 0",
    },
]
