TESTS = [
    {
        "id": "6.1",
        "section": "Control Flow",
        "setup": [": TESTIF IF 111 . ELSE 222 . THEN ;"],
        "input": "1 TESTIF",
        "expect": "111 ",
        "match": "exact",
        "note": "IF/ELSE/THEN: non-zero takes true branch",
    },
    {
        "id": "6.2",
        "section": "Control Flow",
        "setup": [": TESTIF IF 111 . ELSE 222 . THEN ;"],
        "input": "0 TESTIF",
        "expect": "222 ",
        "match": "exact",
        "note": "IF/ELSE/THEN: zero takes else branch",
    },
    {
        "id": "6.3",
        "section": "Control Flow",
        "setup": [": TESTIF2 IF 42 . THEN ;"],
        "input": "1 TESTIF2",
        "expect": "42 ",
        "match": "exact",
        "note": "IF/THEN without ELSE: true branch taken",
    },
    {
        "id": "6.4",
        "section": "Control Flow",
        "setup": [": TESTIF2 IF 42 . THEN ;"],
        "input": "0 TESTIF2",
        "expect": "",
        "match": "exact",
        "note": "IF/THEN without ELSE: false branch produces no output",
    },
    {
        "id": "6.5",
        "section": "Control Flow",
        "setup": [],
        "input": "A .",
        "expect": "10 9 8 7 6 5 4 3 2 1 0 -1 ",
        "match": "exact",
        "note": "BEGIN/UNTIL loop; A is pre-defined at boot; -1 left on stack, printed by .",
    },
    {
        "id": "6.6",
        "section": "Control Flow",
        "setup": [],
        "input": "1 B",
        "expect": "1000 ",
        "match": "exact",
        "note": "B with non-zero: prints 1000",
    },
    {
        "id": "6.7",
        "section": "Control Flow",
        "setup": [],
        "input": "0 B",
        "expect": "2000 ",
        "match": "exact",
        "note": "B with zero: prints 2000",
    },
]
