TESTS = [
    {
        "id": "12.1",
        "section": "Edge Cases",
        "setup": [],
        "input": "2147483647 .",
        "expect": "2147483647 ",
        "match": "exact",
        "note": "Near INT_MAX",
    },
    {
        "id": "12.2",
        "section": "Edge Cases",
        "setup": [],
        "input": "2147483647 1 + .",
        "expect": "-2147483648 ",
        "match": "exact",
        "note": "Signed wrap-around (silent, ARM behaviour)",
    },
    {
        "id": "12.3",
        "section": "Edge Cases",
        "setup": [],
        "input": "0 5 /MOD . .",
        "expect": "0 0 ",
        "match": "exact",
        "note": "Zero dividend: quotient=0 remainder=0",
    },
    {
        "id": "12.4",
        "section": "Edge Cases",
        "setup": [],
        "input": "10 0 /MOD",
        "expect": "division by zero",
        "match": "contains",
        "note": "Division by zero: firmware prints error, discards both operands, returns cleanly",
    },
    {
        "id": "12.5",
        "section": "Edge Cases",
        "setup": [],
        "input": "-7 3 /MOD . .",
        "expect": "-2 -1 ",
        "match": "exact",
        "note": "Signed division truncation toward zero: TOS=quotient(-2), second=remainder(-1)",
    },
]
