TESTS = [
    {
        "id": "2.1",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "5 DUP . .",
        "expect": "5 5 ",
        "match": "exact",
        "note": "DUP copies TOS",
    },
    {
        "id": "2.2",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "1 2 DROP .",
        "expect": "1 ",
        "match": "exact",
        "note": "DROP removes TOS",
    },
    {
        "id": "2.3",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "1 2 SWAP . .",
        "expect": "1 2 ",
        "match": "exact",
        "note": "SWAP ( x1 x2 -- x2 x1 ): x1=1 is new TOS, printed first by . .",
    },
    {
        "id": "2.4",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "3 4 OVER . . .",
        "expect": "3 4 3 ",
        "match": "exact",
        "note": "OVER copies second item to top",
    },
    {
        "id": "2.5",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "1 2 3 ROT . . .",
        "expect": "1 3 2 ",
        "match": "exact",
        "note": "ROT: ( 1 2 3 -- 2 3 1 ), TOS=1 printed first",
    },
    {
        "id": "2.6",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "7 8 2DUP . . . .",
        "expect": "8 7 8 7 ",
        "match": "exact",
        "note": "2DUP = OVER OVER; stack becomes 7 8 7 8",
    },
    {
        "id": "2.7",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "99 NOP .",
        "expect": "99 ",
        "match": "exact",
        "note": "NOP is a no-op",
    },
    {
        "id": "2.8",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "1 2 3 DEPTH . DROP DROP DROP",
        "expect": "3 ",
        "match": "exact",
        "note": "Stack has 3 items; cleanup with DROP DROP DROP",
    },
    {
        "id": "2.9",
        "section": "Stack Manipulation",
        "setup": [],
        "input": "10 20 30 .S DROP DROP DROP",
        "expect": "30 20 10 ",
        "match": "exact",
        "note": "Prints TOS-first; stack 10(bot) 20 30(TOS) → output: 30 20 10",
    },
]
