TESTS = [
    {
        "id": "7.1",
        "section": "Word Definition",
        "setup": [": DOUBLE 2 * ;"],
        "input": "6 DOUBLE .",
        "expect": "12 ",
        "match": "exact",
        "note": "Basic word definition",
    },
    {
        "id": "7.2",
        "section": "Word Definition",
        "setup": [": SUMTHREE + + ;"],
        "input": "1 2 3 SUMTHREE .",
        "expect": "6 ",
        "match": "exact",
        "note": "Word with multiple ops",
    },
    {
        "id": "7.3",
        "section": "Word Definition",
        "setup": [": DOUBLE 2 * ;", ": QUAD DOUBLE DOUBLE ;"],
        "input": "3 QUAD .",
        "expect": "12 ",
        "match": "exact",
        "note": "Nested Forth word calls",
    },
    {
        "id": "7.4",
        "section": "Word Definition",
        "setup": [": ADD5 5 + ;"],
        "input": "10 ADD5 .",
        "expect": "15 ",
        "match": "exact",
        "note": "LIT compiled into word",
    },
    {
        "id": "7.5",
        "section": "Word Definition",
        "setup": [],
        "input": "STATE .",
        "expect": "0 ",
        "match": "exact",
        "note": "STATE=0 in interpret mode",
    },
    {
        "id": "7.6",
        "section": "Word Definition",
        "setup": [": MYIMM 999 . ; IMMEDIATE"],
        "input": ": USEIMM MYIMM ;",
        "expect": "999 ",
        "match": "exact",
        "note": "IMMEDIATE word runs at compile time of USEIMM",
    },
]
